rule download_data:
    params:
        dir_mcd12q1="data/MCD12Q1",
        dir_vnp16a2="data/VNP16A2"
    script:
        "workflows/download_data.py"

rule process_land_cover:
    input:
        "data/MCD12Q1/MCD12Q1.A2023001.h18v05.061.2024252125305.hdf"
    output:
        "data/processed/MODIS_MCD12Q1_Type5_cereal_croplands_h15v05_2023.tiff"
    script:
        "workflows/process_land_cover.py"
